### ISSUE TITLE
One-byte opcode implementation progress

### ISSUE THREAD

**Issue by reisnera** [reisnera/gameboylfb#8]
The following refer to rows in this table: http://www.pastraiser.com/cpu/gameboy/gameboy_opcodes.html
If most of a row is implemented, check the box here but add unimplemented stragglers to #5.
- [x] 0x
- [x] 1x
- [x] 2x
- [x] 3x
- [x] 4x
- [x] 5x
- [x] 6x
- [x] 7x
- [x] 8x
- [x] 9x
- [x] Ax
- [x] Bx - Thompo/Alex
- [x] Cx - Alex
- [x] Dx
- [x] Ex
- [x] Fx

**Comment by apostrophest** [comment]
Got rows 8x and 9x except https://github.com/reisnera/gameboylfb/issues/5#issuecomment-148874864

**Comment by apostrophest** [comment]
Working on Bx
